'use strict';

// tests for accountDocuments
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getUserInfoHandler', '/lib/handlers/getUserInfoHandler.js', 'getUserInfoHandler');

describe('getUserInfoHandler', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      principalId: 'google-oauth2|116434154009969203346'
    }
    return wrapped.run(event).then((response) => {

      expect(response).to.not.be.empty;
    })
  })
})
